### ISSUE TITLE
Learn more about the developers past projects via blog

### ISSUE THREAD

**Issue by m0nq** [m0nq/portfolio#4]
As a prospective client, I want to see a well-organized and visually appealing presentation of the developer's projects.

## Estimated Time
TBD

## Acceptance Criteria
A client can see a list of project showcase that links to a blog post about each project.

Project Showcase:
- [ ] I want to see a well-organized and visually appealing presentation of the developer's projects.
- [ ] For each project, I want a clear title, an image of the front page of the site, and a concise description that highlights the project's scope, key features, and technologies used.
- [ ] I want the option to learn more about a specific project (future feature: link to detailed project description).

**Comment by m0nq** [comment]
Gatsby plugin library for adding headless CMSs https://www.gatsbyjs.com/plugins

Documentation for using plugins https://www.gatsbyjs.com/docs/how-to/plugins-and-themes/
